export const FETCH_EVENT_DATE_LIST = 'FETCH_EVENT_DATE_LIST';
export const FETCH_EVENT_DATE_LIST_SUCCESS = 'FETCH_EVENT_DATE_LIST_SUCCESS';
export const FETCH_EVENT_DATE_LIST_FAILED = 'FETCH_EVENT_DATE_LIST_FAILED';
