export const FETCH_EVENT_DATE_LIST = 'FETCH_EVENT_DATE_LIST';
export const FETCH_EVENT_DATE_LIST_SUCCESS = 'FETCH_EVENT_DATE_LIST_SUCCESS';
export const FETCH_EVENT_DATE_LIST_FAILED = 'FETCH_EVENT_DATE_LIST_FAILED';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
