export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAILED = 'CREATE_NEW_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';

export const FETCH_USER_INFO_FROM_DATABASE = 'FETCH_USER_INFO_FROM_DATABASE';
export const FETCH_USER_INFO_FROM_DATABASE_SUCCESS =
  'FETCH_USER_INFO_FROM_DATABASE_SUCCESS';

export const FETCH_USER_INFO_FROM_SESSION_STORAGE =
  'FETCH_USER_INFO_FROM_SESSION_STORAGE';
export const FETCH_USER_INFO_FROM_SESSION_STORAGE_SUCCESS =
  'FETCH_USER_INFO_FROM_SESSION_STORAGE_SUCCESS';
export const FETCH_USER_INFO_FROM_SESSION_STORAGE_FAILED =
  'FETCH_USER_INFO_FROM_SESSION_STORAGE_FAILED';

export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED';

export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_FAILED = 'SIGNOUT_USER_FAILED';

export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
